services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlkontener
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TwojeHaslo123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data: